### ISSUE TITLE
Mixin Error for 1.20.1 on GNU/Linux

### ISSUE THREAD

**Issue by ghost** [moonwirer/no-more-structures-full-1.21#1]
When using Linux (I'm on Mint 21.3), and I add the mod to Prism Launcher (A MultiMC fork, a fork of PolyMC), I get this Mixin error, as shown here:
`java.lang.RuntimeException: Error creating Mixin config no-more-structures-full.mixins.json for mod no-more-structures-full
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config no-more-structures-full.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more`

How could I fix this strange error?

**Comment by moonwirer** [comment]
Make sure you are using Java 21, I think you are using Java 17.

**Comment by ghost** [comment]
Why would Java 21 be a requirement, when the version I'm running uses Java 17? Would I have to skip Java compatibility checks in Prism Launcher (the launcher I got this report from)?

**Comment by moonwirer** [comment]
I basically forgot to add Java 17 support, I will do when I get back but for now just use Java 21. It works when I use it on any version with MultiMC

**Comment by ghost** [comment]
I got it to work. It was a mixin error with Java 21 on 1.20.1. We can go ahead and close it, since I was being an idiot.
